name: Publish Podcast Episodes

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pensieriincodice:
    runs-on: ubuntu-latest
    environment: pensieriincodice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run publish script
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          RSS_URL: ${{ vars.RSS_URL }}
          TEMPLATE: ${{ vars.TEMPLATE }}
          LAST_PUBLISHED_URL: ${{ vars.LAST_PUBLISHED_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ENVIRONMENT: ${{ github.job }}
        run: python publish.py

  goodvibrations:
    runs-on: ubuntu-latest
    environment: goodvibrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run publish script
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          RSS_URL: ${{ vars.RSS_URL }}
          TEMPLATE: ${{ vars.TEMPLATE }}
          LAST_PUBLISHED_URL: ${{ vars.LAST_PUBLISHED_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ENVIRONMENT: ${{ github.job }}
        run: python publish.py
